# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f9e6efe48c530c85af11deb494f945cc8671e01b47fe1d5c873ffbe2bfa46e4c44d3589cd53e2c63432349ad7412b821d420767d429bea63c2ac41d6567537

test:
  secret_key_base: 737fe0b1113a0d32e1c40395bccb52113a5a04e4ef7498188d5f3d2fe7d38c242727886dd373b3acf6a82801429b9980e27d30cc2514f9c8687ca5bce52d55da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
